#!/usr/bin/env node
// Downloads the web fonts into fonts/ and writes fonts/fonts.css, so the page
// does not depend on Google Fonts at run time.
//
//   node scripts/fetch-fonts.mjs
//
// Only the weights the stylesheet actually uses are requested, and only the
// latin ranges are kept. The unicode-range rules are preserved, so a browser
// still downloads just the range it needs.

import { writeFileSync, mkdirSync, readdirSync, unlinkSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "fonts");

// Space Grotesk 400/700 and Instrument Serif regular/italic. 500 was requested
// historically but no rule ever used it.
const SOURCE =
  "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;700&family=Instrument+Serif:ital@0;1&display=swap";

// Asking as a current browser is what gets woff2 rather than older formats.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36";

const KEEP_RANGES = ["latin", "latin-ext"];

const cssRes = await fetch(SOURCE, { headers: { "User-Agent": UA } });
if (!cssRes.ok) {
  console.error(`Could not fetch the font stylesheet: HTTP ${cssRes.status}`);
  process.exit(2);
}
const css = await cssRes.text();

// Each block is preceded by a /* range */ comment naming its unicode subset.
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)].map(
  ([, range, block]) => ({ range, block }),
);

if (!blocks.length) {
  console.error("Parsed no @font-face blocks; the upstream format may have changed.");
  process.exit(2);
}

mkdirSync(dir, { recursive: true });

const kept = [];
const saved = new Set();
// Space Grotesk is a variable font, so Google serves one file for both 400 and
// 700 and the browser picks the weight off the axis. Keying on the source url
// means those two faces share a file instead of storing it twice.
const byUrl = new Map();

for (const { range, block } of blocks) {
  if (!KEEP_RANGES.includes(range)) continue;

  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? "400";
  const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? "normal";
  if (!url || !family) continue;

  let name = byUrl.get(url);
  if (!name) {
    name = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}${
      style === "italic" ? "-italic" : ""
    }-${range}.woff2`;

    const res = await fetch(url, { headers: { "User-Agent": UA } });
    if (!res.ok) {
      console.error(`Failed to download ${name}: HTTP ${res.status}`);
      process.exit(1);
    }
    writeFileSync(join(dir, name), Buffer.from(await res.arrayBuffer()));
    byUrl.set(url, name);
    saved.add(name);
  }

  kept.push(block.replace(/url\(https:[^)]+\.woff2\)/, `url(./${name})`).trim());
}

// Drop any font file this run did not produce, so the folder cannot drift.
let removed = 0;
for (const file of readdirSync(dir)) {
  if (file.endsWith(".woff2") && !saved.has(file)) {
    unlinkSync(join(dir, file));
    removed += 1;
  }
}

const header = `/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand.
   Space Grotesk and Instrument Serif, both under the SIL Open Font License.
   See fonts/OFL.txt. Re-run the script to refresh. */\n\n`;

writeFileSync(join(dir, "fonts.css"), header + kept.join("\n\n") + "\n");

console.log(`Saved ${saved.size} font files and ${kept.length} @font-face rules.`);
if (removed) console.log(`Removed ${removed} stale font file(s).`);
